# Generated by Django 3.2.5 on 2021-07-03 12:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('shortened_url', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 7, 3, 12, 48, 49, 866263, tzinfo=utc), editable=False)),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
