# Generated by Django 3.2.5 on 2021-07-04 19:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 19, 3, 54, 564095, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 11, 19, 3, 54, 564120, tzinfo=utc), editable=False),
        ),
    ]
