# Generated by Django 3.2.5 on 2021-07-03 13:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 13, 3, 20, 100737, tzinfo=utc), editable=False),
        ),
    ]
